[[AquaCrop]]
arch = "aarch64"
git-tree-sha1 = "c93e2aa5bc9e22028e4e03e9e86807d07259c30b"
libgfortran_version = "5.0.0"
os = "macos"

    [[AquaCrop.download]]
    sha256 = "6e1814f1313354b8e7a4693dec6f345833a348d0254e702372e2818186dfab28"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "aarch64"
git-tree-sha1 = "d013d05c9addb05441a25543e6960fabb26a79dc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "d197e4b8527e7fd5b51bf8af16681ce1ab21bfeeed693e6e7bb037d0bfb7a0bf"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "aarch64"
git-tree-sha1 = "316afbbcb002f3f5d7df1e9988b0d2a6a3db19d4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "41a8a997d6cc274ebe801a5cf5805a99253c2d3973c4bda17e35b613ffb9bc1a"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "aarch64"
git-tree-sha1 = "205658a5bd6328269649c4eaa3ca123161787561"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "2722a6f330d961ee157a8229a175d7d2bcd6bca06ad448bfea33fbd122eb25e5"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "aarch64"
git-tree-sha1 = "04ff9688c64d9037dabbee92e392fc1666806be5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "a6c26a0f9aa9f4f8f546dcded4f1ee7cf8bea3ea1ef863e5bb38eea4ff56f6dc"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "aarch64"
git-tree-sha1 = "4a23365e0e40a6712814b5e00dba4aa2a0568f6d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[AquaCrop.download]]
    sha256 = "ec2001c79cda32ee8dc9bf20c7edb1df58ceecefbbb035e50808593dcbc2b10f"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "aarch64"
git-tree-sha1 = "613794c175488f86a68c79b24d006f745b41bf0a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[AquaCrop.download]]
    sha256 = "a954de5f44491b24e5e7e26f9488babb1115636a93ae27d40d32a07533615497"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0bac21dfc59e3da6caa301e4afdbd366f5ea93d2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "8ee780d46fc03557e6e960354f81242521e2325e92ef02004a00c2dfa8dc5b2b"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "86c2696fd286bad153dff9ec7556d95853d7641b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "828b839b85d6c30129f426794d3dd3005bff83a10db38ac9c1b03b73cab3ea67"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f71397b8b484996c6c03aff0fc74e302960182b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "d0bec315a092f52b69a6abe4af4c070cf21298780ab8bce99ac1e8e5e26010fc"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d665fd875928ef9d21db44e880b6c4555a2f935"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "b95367a1c82162f38cc1d8a1591b9543ea77a85d9c3203ebd9f0239e5cef4d28"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5dbdfe7c6cfa8d341e428809ef353830972fc786"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "683493ede8d0f6e61f56ed1b4be45e5b6b35d8d9a6ddab6c39b5bd44684ee375"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "90a081724cc4ccf5f8df955999509cd2e9b1da09"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "a17b975f18bbccd37faf515413a05586d269b22d46333349683988df4112b78a"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44f2983bc4c4b6cfc102dd9f97ff31050e535fc3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "6640deabc0c3a999c8b16df9f0d06108286dbb525a37faf52b73896477648a4b"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d08f80c2098a56322affdd4c7f882fb7d1f5fe8b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "15a5402323c0fe25597f0673beba152c0ec3dcd010872afed91667df770ff81f"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "i686"
git-tree-sha1 = "2965440d372abd3e08ffc3822d6df8b69934a427"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "f2ade17fe22786552fa71eec12a3354b0d75e2ada666aba0d821e3a4dfb56e12"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.i686-linux-gnu-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "i686"
git-tree-sha1 = "4a9f8e9ee1c57c3a6f36a3cd6b6d0247dc405506"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "b09c6f83f5e5447aa4fdc5871d9c9d1d0e3f9b8307fc083179b89e271adea8ca"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.i686-linux-gnu-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "i686"
git-tree-sha1 = "13b01c4abefda40233987f0651687a197c1c33a5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "5aa1bfa25a4064cd652bf936526df1f75b49cb5008981ebc283c4c08215ae855"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.i686-linux-musl-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "i686"
git-tree-sha1 = "653bd812a7d89eb3d5f2cb089540ba093a1cfc94"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "1dc98713ab62c0d80919685be3ea0389f4cf440dd81e5c5df580f093f7c36a6f"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.i686-linux-musl-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "i686"
git-tree-sha1 = "edf4352a01f2d764ec1390b5a5b83c5680c3a748"
libgfortran_version = "4.0.0"
os = "windows"

    [[AquaCrop.download]]
    sha256 = "ed499c67215d4850d5dba2a824db1d61f19fa2545652392c74ea00f1583e5004"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "i686"
git-tree-sha1 = "60a17c35bc68d115e675cb7121617a520d0e614d"
libgfortran_version = "5.0.0"
os = "windows"

    [[AquaCrop.download]]
    sha256 = "e2235b1529780488b43d7e1330f927ea7d2b0824c6f4ffe513a6ed922d3dbc45"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "powerpc64le"
git-tree-sha1 = "0691d247cfdb98d64c370a84b7f32026340ea3f8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "4cad73347500892d75769949e4c5baa460aa7ed7862d29f3882336043a82feee"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "powerpc64le"
git-tree-sha1 = "4b97b639112bb7e779ffe87400b89ab14895d5bd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "33c67c469296dc8b19fe716532f120e89990bcddd52b718d5e52d7bb38731e7c"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "riscv64"
git-tree-sha1 = "37f8fc0405e88313393fbf453ad1d04dfe509bb7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "d8b2f5bd13f6ee77c89bb955900ac0fd29accf535897645c0e15de30815e6785"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "x86_64"
git-tree-sha1 = "ed06846fb94656f618b546288451b62fb37463d6"
libgfortran_version = "4.0.0"
os = "macos"

    [[AquaCrop.download]]
    sha256 = "2bd598ca7bc2b69ea838b2bf7803a39e6c3456a5963a8d902a19ede0ca05b647"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "x86_64"
git-tree-sha1 = "a0ae225cecb9fbb640ac445ff5bb241ef1bcb9cc"
libgfortran_version = "5.0.0"
os = "macos"

    [[AquaCrop.download]]
    sha256 = "cbc912a403f42953d0f4605f5b4f5cca2066eb7e19f5e15c5e8d213575bf50df"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "x86_64"
git-tree-sha1 = "990f62e38d682e4805b7be196da9560c49e3ec90"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "3da563bdffcdc1c324e09685ccde4e01708c1b0914fd871c5d2467b4baa9b53c"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "x86_64"
git-tree-sha1 = "fbfa4f95a817112074cb457eeb2fd06b1cc645bd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "884b401c69c0b397fef9ae7e7bccc309fa3e08a12696a28772ac5412fefe2ca7"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "x86_64"
git-tree-sha1 = "414269a80fd1223955299cc53f86ad07d7748786"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "a2ca0d83f667fb33c22830d22e1b15d85e1792bf30e2e6fd6c42650ca1976e6a"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "x86_64"
git-tree-sha1 = "0e915f3ed0ed20fb25db0c14946cc575f491c1d1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[AquaCrop.download]]
    sha256 = "2ca015d3dc3ba01da2e7351be6d2efd23c797b3069c78e411774c585b1ea6380"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "x86_64"
git-tree-sha1 = "d537271d9181414200b97eaa53fd74cadb4274c9"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[AquaCrop.download]]
    sha256 = "4bb02773989ecdab8c36a496a703097e5bcbbd2f6b9e91b769f0278ea63d66f5"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "x86_64"
git-tree-sha1 = "12f33497f0783d683c4be178e8888df143fae38c"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[AquaCrop.download]]
    sha256 = "bec7a62e164caeed790e753e7ea388c9160b60e43d8fbc9d5a674401a8c9f700"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[AquaCrop]]
arch = "x86_64"
git-tree-sha1 = "c468ac26727fa1daa4c43322a414b0b39e183246"
libgfortran_version = "4.0.0"
os = "windows"

    [[AquaCrop.download]]
    sha256 = "36481e506f1c0c82e6cc3a6a2ad1b2c84eb758a284eb24785b71b045a075e029"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[AquaCrop]]
arch = "x86_64"
git-tree-sha1 = "7c1ee978e88a84b5df4202b083f96cc423c9c637"
libgfortran_version = "5.0.0"
os = "windows"

    [[AquaCrop.download]]
    sha256 = "40e4afd0e0134d7da80da4a47697758a21b6913e6ceaee6a376503c71865ed48"
    url = "https://github.com/JuliaBinaryWrappers/AquaCrop_jll.jl/releases/download/AquaCrop-v7.1.1+0/AquaCrop.v7.1.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
