# Autogenerated wrapper script for AquaCrop_jll for aarch64-apple-darwin-libgfortran5
export aquacrop, libaquacrop

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("AquaCrop")
JLLWrappers.@declare_library_product(libaquacrop, "@rpath/libaquacrop.dylib")
JLLWrappers.@declare_executable_product(aquacrop)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libaquacrop,
        "lib/libaquacrop.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        aquacrop,
        "bin/aquacrop",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
